version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.18.0
    commands:
      - echo Installing Node.js...
  pre_build:
    commands: -npm install
  build:
    commands: -npm run build
  post_build:
    commands: -aws s3 cp --recursive .build s3://oleg-react-deployment
  # -aws cloudfront create-invalidation --distribution-id
